config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get 'download_pdf_document'
    end
  end
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

#   include PdfDocumentUploader::Attachment.new(:pdf_document)

  field :name, type: String
  field :email, type: String
  field :pdf_document, type: BSON::Binary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if params[:user][:pdf_document].present?
      # Lê os dados binários do arquivo enviado
      pdf_data = params[:user][:pdf_document].read
      # Define os dados binários do PDF no modelo User
      @user.pdf_document = BSON::Binary.new(pdf_data, :generic)
    end

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def download_pdf_document
    @user = User.find(params[:id])
    send_data @user.pdf_document.data, filename: 'document.pdf', type: 'application/pdf', disposition: 'attachment'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :pdf_document)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <!-- Adicione um campo para upload de arquivo PDF -->
  <div class="field">
    <%= form.label :pdf_document, 'Documento PDF' %>
    <%= form.file_field :pdf_document %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Lista de Usuários</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %> - <%= user.email %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Cadastrar Novo Usuário</h1>

<%= form_with(model: @user, url: users_path, local: true, multipart: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :pdf_document, 'PDF Document' %>
    <%= f.file_field :pdf_document %>
  </div>

  <div class="actions">
    <%= f.submit "Cadastrar Usuário" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Detalhes do Usuário</h1>

<p><strong>Nome:</strong> <%= @user.name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>

<% if @user.pdf_document.present? %>
  <p><strong>PDF Document:</strong> <%= link_to 'Baixar PDF', download_pdf_document_user_path(@user) %></p>
<% else %>
  <p>Nenhum documento PDF associado a este usuário.</p>
<% end %>